# Generated by Django 3.0 on 2020-05-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empmodel',
            name='NAME',
        ),
        migrations.RemoveField(
            model_name='empmodel',
            name='SALARY',
        ),
        migrations.AddField(
            model_name='empmodel',
            name='cpassword',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empmodel',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='empmodel',
            name='name',
            field=models.CharField(default='2', max_length=50),
        ),
        migrations.AddField(
            model_name='empmodel',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='empmodel',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
